# Generated by Django 2.0.7 on 2018-08-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20180805_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': (('can_author_change', 'Create, update and delete authors'),)},
        ),
    ]
