# Generated by Django 2.0.7 on 2018-08-06 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20180806_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_book_change', 'Create, update and delete books'),)},
        ),
    ]
